[package]
name = "branch-and-bound"
description = "Branch and Bound / Backtracking algorithms generic template library"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/kolayne/Branch-and-Bound-templates"
readme = "README.md"

[dependencies]
